#page title
page_title: One Plan # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 1501523700 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link:
  # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/appicon.png # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: One Plan # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: £1.99 # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Put your training plan in the palm of your hand. Whether you're training for your first 5K or just want to schedule your regular training sessions, Oneplan lets you enter your own plan or amend a preset plan to schedule and tick off your training sessions, around your busy schedule. Your plan, your way!

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: OnePlan Apps Ltd
your_link: https://oneplan.app
your_city: London, United kingdom
email_address: hello@oneplan.app
facebook_username:
instagram_username: oneplan.social
twitter_username: oneplan.social
github_username:
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Take your plan off the Fridge
    description: With Oneplan, you'll always have your training plan with you. Mark off activities as you do them, or mark them as not done, it's easy.
    fontawesome_icon_name: magic

  - title: See your Progress
    description: Track simple statistics against your plan, to see how you're performing week on week.
    fontawesome_icon_name: chart-line

  - title: MultiSport, Multiplan
    description: Add different sports to a single plan, or manage multiple plans for different events. Set up repeating activities for those regular sessions each week. Whatever best suits you.
    fontawesome_icon_name: football-ball

  - title: Calendar Integration
    description: Everyone is busy so why not see your training plan alongside your calendars and decide when the best dates and times are to train. And if a meeting comes up you can't avoid, move that activity to another day!
    fontawesome_icon_name: sync

  - title: Easy Reminders
    description: Setup custom notifications for each activity or generic plan notifications. Never miss a training activity because your piece of paper on the refrigerator didn't tell you!
    fontawesome_icon_name: bell

  - title: We understand life get's in the way
    description: No streaks to lose, no disappointment. Sometimes you just can't train, whether it's work, tiredness, social, we understand. Just mark an activity as missed and move on. Your motivation is to make the next activity, for you.
    fontawesome_icon_name: smile-wink

  - title: # New Feature Title
    description: # New Feature Description
    fontawesome_icon_name: # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: white # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
